### ISSUE TITLE
[kube-state-metrics] Race condition in GitHub workflow

### ISSUE THREAD

**Issue by dotdc** [prometheus-community/helm-charts#2658]
### Describe the bug a clear and concise description of what the bug is.

When merging PR https://github.com/prometheus-community/helm-charts/pull/2652, the GitHub workflow failed with the error:

```
Error: signing [ghcr.io/prometheus-community/charts/kube-state-metrics:state-metrics-4.22.2]: accessing entity: entity not found in registry
main.go:62: error during command execution: signing [ghcr.io/prometheus-community/charts/kube-state-metrics:state-metrics-4.22.2]: accessing entity: entity not found in registry
```

Didn't had time to check but this could be a race condition that could have been introduced in PR https://github.com/prometheus-community/helm-charts/pull/2631.

Failed attempt : https://github.com/prometheus-community/helm-charts/actions/runs/3414205456/jobs/5681851342

Worked on re-run.

@scottrigby @monotek 

### What's your helm version?

N/A

### What's your kubectl version?

N/A

### Which chart?

kube-state-metrics

### What's the chart version?

4.22.2

### Enter the command that you execute and failing/misfunctioning.

Failed attempt: https://github.com/prometheus-community/helm-charts/actions/runs/3414205456/jobs/5681851342

**Comment by dotdc** [comment]
Reopening, same behavior : 
https://github.com/prometheus-community/helm-charts/actions/runs/3419543623/jobs/5693197735

**Comment by dotdc** [comment]
Seems fine now :+1:
